import markdown
from xhtml2pdf import pisa
import os

def convert_md_to_pdf(md_file_path, pdf_file_path):
    # Read the markdown file
    with open(md_file_path, 'r', encoding='utf-8') as f:
        md_content = f.read()

    # Convert markdown to HTML
    html_content = markdown.markdown(md_content, extensions=['extra', 'tables', 'fenced_code'])

    # Add some basic styling for the PDF
    styled_html = f"""
    <html>
    <head>
        <style>
            @page {{
                size: a4;
                margin: 2cm;
            }}
            body {{
                font-family: Arial, sans-serif;
                font-size: 12pt;
                line-height: 1.5;
                color: #333;
            }}
            h1 {{ color: #2c3e50; text-align: center; border-bottom: 1px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; border-bottom: 1px solid #eee; padding-bottom: 5px; margin-top: 20px; }}
            h3 {{ color: #16a085; }}
            code {{ background-color: #f8f8f8; padding: 2px 5px; border-radius: 3px; font-family: Courier, monospace; }}
            pre {{ background-color: #f8f8f8; padding: 10px; border-radius: 5px; overflow-x: auto; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
            img {{ max-width: 100%; height: auto; display: block; margin: 20px auto; }}
            .footer {{ text-align: center; font-size: 10pt; color: #7f8c8d; margin-top: 50px; }}
        </style>
    </head>
    <body>
        {html_content}
        <div class="footer">Generated by AI Assistant - Cognifyz Internship Project</div>
    </body>
    </html>
    """

    # Utility function to resolve image paths for xhtml2pdf
    def link_callback(uri, rel):
        if uri.startswith('http'):
            return uri
        # Resolve local paths
        path = os.path.join(os.path.dirname(md_file_path), uri)
        return path

    # Create the PDF
    with open(pdf_file_path, "wb") as pdf_file:
        pisa_status = pisa.CreatePDF(styled_html, dest=pdf_file, link_callback=link_callback)

    return not pisa_status.err

if __name__ == "__main__":
    success = convert_md_to_pdf('report.md', 'Restaurant_Data_Analysis_Report.pdf')
    if success:
        print("Successfully created Restaurant_Data_Analysis_Report.pdf")
    else:
        print("Error creating PDF")
