import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { email, cityName, stats } = body;

    // 1. Configure SMTP Transporter
    // In production, these should come from process.env
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: Number(process.env.SMTP_PORT) || 465,
      secure: true, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // 2. Prepare Email Content
    const mailOptions = {
      from: process.env.SMTP_FROM || '"DineAnalytics Reports" <reports@dineanalytics.com>',
      to: email,
      subject: `📊 Market Intelligence Report: ${cityName}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #111; border-bottom: 2px solid #FACC15; padding-bottom: 10px;">DineAnalytics Intelligence Report</h2>
          <p>Hello,</p>
          <p>Attached is the custom market analysis you requested for <strong>${cityName}</strong>.</p>
          
          <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #111;">Market Summary for ${cityName}</h3>
            <ul style="list-style: none; padding: 0;">
              <li style="margin-bottom: 10px;">🏙️ <strong>Market Density:</strong> ${stats.count} Venues</li>
              <li style="margin-bottom: 10px;">⭐ <strong>Quality Index:</strong> ${stats.avgRating} / 5.0</li>
              <li style="margin-bottom: 10px;">💰 <strong>Economic Index:</strong> ₹${stats.avgCost} (Avg for 2)</li>
              <li style="margin-bottom: 10px;">🍽️ <strong>Top Cuisine:</strong> ${stats.topCuisine}</li>
            </ul>
          </div>

          <p style="font-size: 14px; color: #666;">This report was automatically generated by the DineAnalytics Engine. For deep-dive comparison and predictive insights, please visit your dashboard.</p>
          
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 12px; color: #999; text-align: center;">© 2026 DineAnalytics. All rights reserved.</p>
        </div>
      `,
    };

    // 3. Send the Email
    // Note: To send a real PDF, you would use a library like 'jspdf' to generate a buffer
    // and add it to the 'attachments' array in mailOptions.
    await transporter.sendMail(mailOptions);

    return NextResponse.json({ 
      success: true, 
      message: `Analysis for ${cityName} has been successfully dispatched to ${email}!` 
    });
  } catch (error: any) {
    console.error("Email error:", error);
    return NextResponse.json({ 
      success: false, 
      error: error.message || "Failed to transmit report. Check SMTP configuration." 
    }, { status: 500 });
  }
}
